# Generated by Django 6.0.5 on 2026-05-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
